export const products = [
  {
    id: 1,
    name: "Cute Articulated Dinosaur",
    description:
      "A highly detailed custom figurine perfect for collectors. This adorable dinosaur features articulated joints and comes in vibrant colors.",
    price: 17.28,
    originalPrice: 48.0,
    image: "/placeholder.svg",
    rating: 4.5,
    category: "Toys & Games",
    sku: "2.51.594",
    stock: "In Stock",
  },
  {
    id: 2,
    name: "3D Printed Vase",
    description:
      "Beautiful and unique 3D printed vase for your home decor. Each piece is carefully crafted to add a touch of elegance to any room.",
    price: 29.99,
    originalPrice: 49.99,
    image: "/placeholder.svg",
    rating: 4.0,
    category: "Home Decor",
    sku: "2.51.595",
    stock: "In Stock",
  },
  {
    id: 3,
    name: "Gadget Holder",
    description:
      "A practical and stylish holder for your everyday gadgets. Keep your desk organized and your devices easily accessible.",
    price: 19.99,
    originalPrice: 29.99,
    image: "/placeholder.svg",
    rating: 4.2,
    category: "Gadgets",
    sku: "2.51.596",
    stock: "In Stock",
  },
  {
    id: 4,
    name: "Custom Keychain",
    description:
      "Personalized 3D printed keychain with your design. A perfect gift or a unique accessory to showcase your style.",
    price: 9.99,
    originalPrice: 14.99,
    image: "/placeholder.svg",
    rating: 4.8,
    category: "Accessories",
    sku: "2.51.597",
    stock: "In Stock",
  },
  {
    id: 5,
    name: "Desk Organizer",
    description:
      "Keep your workspace tidy with this 3D printed desk organizer. Features multiple compartments for all your office essentials.",
    price: 24.99,
    originalPrice: 34.99,
    image: "/placeholder.svg",
    rating: 4.3,
    category: "Home Decor",
    sku: "2.51.598",
    stock: "In Stock",
  },
  {
    id: 6,
    name: "Miniature City Set",
    description:
      "Create your own miniature city with this detailed 3D printed set. Includes various buildings and landmarks for endless play possibilities.",
    price: 59.99,
    originalPrice: 79.99,
    image: "/placeholder.svg",
    rating: 4.7,
    category: "Toys & Games",
    sku: "2.51.599",
    stock: "In Stock",
  },
  {
    id: 7,
    name: "Customizable Phone Case",
    description:
      "Protect your phone in style with this customizable 3D printed phone case. Choose your design and make it uniquely yours.",
    price: 14.99,
    originalPrice: 24.99,
    image: "/placeholder.svg",
    rating: 4.4,
    category: "Accessories",
    sku: "2.51.600",
    stock: "In Stock",
  },
  {
    id: 8,
    name: "3D Printed Planter",
    description:
      "Add a modern touch to your indoor garden with this 3D printed planter. Perfect for small succulents and herbs.",
    price: 19.99,
    originalPrice: 29.99,
    image: "/placeholder.svg",
    rating: 4.6,
    category: "Home Decor",
    sku: "2.51.601",
    stock: "In Stock",
  },
  {
    id: 9,
    name: "Robotic Arm Kit",
    description:
      "Build your own robotic arm with this 3D printed kit. Great for learning about mechanics and robotics.",
    price: 79.99,
    originalPrice: 99.99,
    image: "/placeholder.svg",
    rating: 4.9,
    category: "Gadgets",
    sku: "2.51.602",
    stock: "In Stock",
  },
  {
    id: 10,
    name: "Custom Chess Set",
    description:
      "A unique chess set with 3D printed pieces. Choose your own designs for a truly personalized game experience.",
    price: 49.99,
    originalPrice: 69.99,
    image: "/placeholder.svg",
    rating: 4.8,
    category: "Toys & Games",
    sku: "2.51.603",
    stock: "In Stock",
  },
  {
    id: 11,
    name: "3D Printed Wall Clock",
    description:
      "A modern and stylish wall clock made with 3D printing technology. Silent mechanism for a peaceful environment.",
    price: 34.99,
    originalPrice: 44.99,
    image: "/placeholder.svg",
    rating: 4.5,
    category: "Home Decor",
    sku: "2.51.604",
    stock: "In Stock",
  },
  {
    id: 12,
    name: "Customizable Jewelry Box",
    description:
      "Store your precious items in this elegant, customizable 3D printed jewelry box. Multiple compartments for organization.",
    price: 39.99,
    originalPrice: 54.99,
    image: "/placeholder.svg",
    rating: 4.7,
    category: "Accessories",
    sku: "2.51.605",
    stock: "In Stock",
  },
  {
    id: 13,
    name: "3D Printed Drone Frame",
    description:
      "Build your own custom drone with this lightweight yet durable 3D printed frame. Compatible with standard components.",
    price: 69.99,
    originalPrice: 89.99,
    image: "/placeholder.svg",
    rating: 4.6,
    category: "Gadgets",
    sku: "2.51.606",
    stock: "In Stock",
  },
  {
    id: 14,
    name: "Architectural Model Kit",
    description:
      "Create stunning architectural models with this 3D printed kit. Ideal for students, professionals, or hobbyists.",
    price: 89.99,
    originalPrice: 109.99,
    image: "/placeholder.svg",
    rating: 4.8,
    category: "Toys & Games",
    sku: "2.51.607",
    stock: "In Stock",
  },
  {
    id: 15,
    name: "Custom Lithophane Lamp",
    description:
      "Turn your favorite photo into a beautiful 3D printed lithophane lamp. A unique way to display your memories.",
    price: 44.99,
    originalPrice: 59.99,
    image: "/placeholder.svg",
    rating: 4.9,
    category: "Home Decor",
    sku: "2.51.608",
    stock: "In Stock",
  },
]

export const categories = ["All", "Toys & Games", "Home Decor", "Gadgets", "Accessories"]

