export const products = [
  {
    id: 1,
    name: "Cute Articulated Dinosaur",
    description:
      "A highly detailed custom figurine perfect for collectors. This adorable dinosaur features articulated joints and comes in vibrant colors.",
    price: 17.28,
    originalPrice: 48.0,
    image: "/placeholder-product-1.jpg",
    rating: 4.5,
    category: "Toys & Games",
    sku: "2.51.594",
    stock: "In Stock",
  },
  {
    id: 2,
    name: "3D Printed Vase",
    description: "Beautiful and unique 3D printed vase for your home decor.",
    price: 29.99,
    originalPrice: 49.99,
    image: "/placeholder-product-2.jpg",
    rating: 4.0,
    category: "Home Decor",
    sku: "2.51.595",
    stock: "In Stock",
  },
  {
    id: 3,
    name: "Gadget Holder",
    description: "A practical and stylish holder for your everyday gadgets.",
    price: 19.99,
    originalPrice: 29.99,
    image: "/placeholder-product-3.jpg",
    rating: 4.2,
    category: "Gadgets",
    sku: "2.51.596",
    stock: "In Stock",
  },
  {
    id: 4,
    name: "Custom Keychain",
    description: "Personalized 3D printed keychain with your design.",
    price: 9.99,
    originalPrice: 14.99,
    image: "/placeholder-product-4.jpg",
    rating: 4.8,
    category: "Accessories",
    sku: "2.51.597",
    stock: "In Stock",
  },
  {
    id: 5,
    name: "Desk Organizer",
    description: "Keep your workspace tidy with this 3D printed desk organizer.",
    price: 24.99,
    originalPrice: 34.99,
    image: "/placeholder-product-5.jpg",
    rating: 4.3,
    category: "Home Decor",
    sku: "2.51.598",
    stock: "In Stock",
  },
  {
    id: 6,
    name: "Miniature City Set",
    description: "Create your own miniature city with this detailed 3D printed set.",
    price: 59.99,
    originalPrice: 79.99,
    image: "/placeholder-product-6.jpg",
    rating: 4.7,
    category: "Toys & Games",
    sku: "2.51.599",
    stock: "In Stock",
  },
]

export const categories = ["All", "Toys & Games", "Home Decor", "Gadgets", "Accessories"]

